<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/VectorSpace.Skia/VectorSpace.Skia.csproj" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="$(VectorSpaceSkiaVersion)" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />
  </ItemGroup>
</Project>
